# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-07 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tb_Departamento',
            fields=[
                ('id_departamento', models.AutoField(primary_key=True, serialize=False)),
                ('dep_nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tb_Pais',
            fields=[
                ('id_pais', models.AutoField(primary_key=True, serialize=False)),
                ('pais_nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='tb_departamento',
            name='pais_id_departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrarUsuarios.tb_Pais'),
        ),
    ]
