# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-08 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrarUsuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_Municipio',
            fields=[
                ('id_municipio', models.AutoField(primary_key=True, serialize=False)),
                ('mun_nombre', models.CharField(max_length=100)),
                ('dep_id_municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrarUsuarios.tb_Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='tb_Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('usr_usuario', models.CharField(max_length=50, unique=True)),
                ('usr_nombres', models.CharField(max_length=100)),
                ('usr_apellidos', models.CharField(max_length=100)),
                ('usr_email', models.EmailField(max_length=254)),
                ('usr_password', models.CharField(max_length=20)),
                ('usr_photo', models.ImageField(upload_to='photos/')),
            ],
        ),
    ]
