# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-14 16:43
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registrarUsuarios', '0002_tb_municipio_tb_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_usuario',
            name='usr_relacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
